[book]
authors = ["Kevin Sullivan"]
language = "en"
multilingual = false
src = "src"
title = "Discrete Mathematics and Theory in Lean 4"

[build]
build-dir = "book"

[output.html]
additional-js = ["assets/lean.min.js"]
mathjax-support = true

[output.html.playground.boring-prefixes]
lean = "# "
